import { Darker_Grotesque, Figtree, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import FooterWrapper from "@/components/Layout/Homepage/FooterWrapper";

const darkerGrotesque = Darker_Grotesque({
  variable: "--font-darkerGrotesque",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-openSans",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${darkerGrotesque.variable} ${openSans.variable} ${figtree.variable} ${poppins.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <FooterWrapper/>
      </body>
    </html>
  );
}
